---
efiSystemPartition: "/boot/efi"
efiSystemPartitionSize: 512MiB
efiSystemPartitionName: EFI

userSwapChoices:
    - none
    - file

initialPartitioningChoice: erase
initialSwapChoice: file

drawNestedPartitions: true
defaultFileSystemType: "ext4"
availableFileSystemTypes: [ "ext4" ]

enableLuksAutomatedPartitioning: false

partitionLayout:
    - name: "LinuxMint"
      filesystem: "ext4"
      mountPoint: "/"
      size: 100%
